import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#11131a",
        surface: "#11131a",
        "on-background": "#e1e2eb",
        "on-surface": "#e1e2eb",
        "on-error-container": "#ffdad6",
        "inverse-on-surface": "#2e3038",
        "on-tertiary-fixed-variant": "#5c4300",
        "on-tertiary-fixed": "#261a00",
        "primary-fixed": "#d8e2ff",
        outline: "#8c909f",
        "surface-dim": "#11131a",
        "on-primary": "#002e69",
        "on-primary-container": "#00285c",
        "surface-container-low": "#191b22",
        "on-secondary-fixed": "#002108",
        "inverse-surface": "#e1e2eb",
        "surface-container-high": "#272a31",
        "primary-container": "#4d8efe",
        "secondary-container": "#30a550",
        tertiary: "#fbbc06",
        "on-tertiary": "#402d00",
        "on-error": "#690005",
        "surface-tint": "#adc6ff",
        "on-secondary": "#003914",
        "secondary-fixed-dim": "#6ddd81",
        "error-container": "#93000a",
        "on-primary-fixed": "#001a41",
        "outline-variant": "#424753",
        secondary: "#6ddd81",
        primary: "#adc6ff",
        "surface-container-highest": "#32353c",
        "tertiary-fixed-dim": "#fbbc06",
        "secondary-fixed": "#89fa9b",
        "primary-fixed-dim": "#adc6ff",
        "tertiary-container": "#b88900",
        "surface-bright": "#363940",
        "on-secondary-fixed-variant": "#005320",
        "surface-container": "#1d2026",
        "on-secondary-container": "#003210",
        "inverse-primary": "#005ac1",
        "surface-variant": "#32353c",
        "tertiary-fixed": "#ffdea0",
        "on-primary-fixed-variant": "#004494",
        error: "#ffb4ab",
        "surface-container-lowest": "#0b0e15",
        "on-tertiary-container": "#372700",
        "on-surface-variant": "#c2c6d5",
        "google-blue": "#4285F4",
        "google-red": "#EA4335",
        "google-yellow": "#FBBC05",
        "google-green": "#34A853",
        success: "#34A853",
        danger: "#EA4335",
        warning: "#FBBC05",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
      },
      spacing: {
        "max-width": "1280px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        gutter: "24px",
        unit: "8px",
      },
      fontFamily: {
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "title-lg": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-lg": [
          "28px",
          {
            lineHeight: "36px",
            letterSpacing: "-0.02em",
            fontWeight: "600",
          },
        ],
        "headline-lg-mobile": [
          "22px",
          { lineHeight: "30px", fontWeight: "600" },
        ],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "title-lg": ["18px", { lineHeight: "26px", fontWeight: "500" }],
        "body-lg": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "body-md": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-lg": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.1px",
            fontWeight: "500",
          },
        ],
        "label-sm": [
          "11px",
          {
            lineHeight: "16px",
            letterSpacing: "0.5px",
            fontWeight: "500",
          },
        ],
      },
      animation: {
        "pulse-line": "pulse-line 4s infinite linear",
      },
      keyframes: {
        "pulse-line": {
          "0%": { transform: "translateY(-100%)", opacity: "0" },
          "50%": { opacity: "1" },
          "100%": { transform: "translateY(100%)", opacity: "0" },
        },
      },
    },
  },
};

export default config;
